USE retail_profit_leakage;
SHOW TABLES;

SELECT COUNT(*) AS total_rows
FROM final_retail_dataset;

SELECT *
FROM final_retail_dataset
LIMIT 5;

DESCRIBE final_retail_dataset;
-- ============================================================
-- Executive Dashboard KPIs
-- ============================================================


SELECT
    SUM(inflation_rate IS NULL) AS missing_inflation,
    SUM(gdp_growth IS NULL) AS missing_gdp
FROM final_retail_dataset;

-- ============================================================
-- What is the total sales generated by the company?
-- ============================================================

SELECT
    ROUND(SUM(sales), 2) AS total_sales
FROM final_retail_dataset;

-- ============================================================
-- What is the total profit earned by the company?
-- ============================================================

SELECT
    ROUND(SUM(profit), 2) AS total_profit
FROM final_retail_dataset;

-- ============================================================
-- How many orders were placed by customers?
-- ============================================================

SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM final_retail_dataset;

-- ============================================================
-- How many unique customers made purchases?
-- ============================================================

SELECT
    COUNT(DISTINCT customer_id) AS total_customers
FROM final_retail_dataset;

-- ============================================================
-- What is the average order value?
-- ============================================================

SELECT
    ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS average_order_value
FROM final_retail_dataset;

-- ============================================================
-- What is the average profit earned per order?
-- ============================================================

SELECT
    ROUND(SUM(profit) / COUNT(DISTINCT order_id), 2) AS average_profit_per_order
FROM final_retail_dataset;
-- ============================================================
-- What is the average discount offered?
-- ============================================================

SELECT
    ROUND(AVG(discount), 2) AS average_discount
FROM final_retail_dataset;
-- ============================================================
-- What is the average shipping cost per order?
-- ============================================================

SELECT
    ROUND(AVG(shipping_cost), 2) AS average_shipping_cost
FROM final_retail_dataset;
-- ============================================================
-- What is the overall profit margin percentage?
-- ============================================================

SELECT
    ROUND((SUM(profit) / SUM(sales)) * 100, 2) AS profit_margin_percentage
FROM final_retail_dataset;
-- ============================================================
-- What is the total quantity of products sold?
-- ============================================================

SELECT
    SUM(quantity) AS total_quantity_sold
FROM final_retail_dataset;
-- ============================================================
-- Which product category generates the highest sales?
-- ============================================================

SELECT
    category,
    ROUND(SUM(sales), 2) AS total_sales
FROM final_retail_dataset
GROUP BY category
ORDER BY total_sales DESC;
-- ============================================================
-- Which product category generates the highest profit?
-- ============================================================

SELECT
    category,
    ROUND(SUM(profit), 2) AS total_profit
FROM final_retail_dataset
GROUP BY category
ORDER BY total_profit DESC;
-- ============================================================
-- Which sub-category generates the highest sales?
-- ============================================================

SELECT
    sub_category,
    ROUND(SUM(sales), 2) AS total_sales
FROM final_retail_dataset
GROUP BY sub_category
ORDER BY total_sales DESC;
-- ============================================================
-- Which sub-category generates the highest profit?
-- ============================================================

SELECT
    sub_category,
    ROUND(SUM(profit), 2) AS total_profit
FROM final_retail_dataset
GROUP BY sub_category
ORDER BY total_profit DESC;
-- ============================================================
-- Which products generate the highest sales?
-- ============================================================

SELECT
    product_name,
    ROUND(SUM(sales), 2) AS total_sales
FROM final_retail_dataset
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 10;
-- ============================================================
-- Which products generate the lowest profit?
-- ============================================================

SELECT
    product_name,
    ROUND(SUM(profit), 2) AS total_profit
FROM final_retail_dataset
GROUP BY product_name
ORDER BY total_profit ASC
LIMIT 10;


-- ============================================================
-- Which sub-categories are making a loss?
-- ============================================================

SELECT
    sub_category,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY sub_category
HAVING SUM(profit) < 0
ORDER BY total_profit;
-- ============================================================
-- Which products are sold with the highest average discount?
-- ============================================================

SELECT
    product_name,
    ROUND(AVG(discount)*100,2) AS average_discount_percentage
FROM final_retail_dataset
GROUP BY product_name
ORDER BY average_discount_percentage DESC
LIMIT 10;
-- ============================================================
-- Which products have the highest shipping cost?
-- ============================================================

SELECT
    product_name,
    ROUND(AVG(shipping_cost),2) AS average_shipping_cost
FROM final_retail_dataset
GROUP BY product_name
ORDER BY average_shipping_cost DESC
LIMIT 10;
-- ============================================================
-- Which countries generate the highest losses?
-- ============================================================

SELECT
    country,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY country
ORDER BY total_profit ASC
LIMIT 10;
-- ============================================================
-- Which customers generated the highest losses?
-- ============================================================

SELECT
    customer_name,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY customer_name
ORDER BY total_profit ASC
LIMIT 10;
-- ============================================================
-- Which markets have the lowest profit margin?
-- ============================================================

SELECT
    market,
    ROUND((SUM(profit)/SUM(sales))*100,2) AS profit_margin_percentage
FROM final_retail_dataset
GROUP BY market
ORDER BY profit_margin_percentage ASC;
-- ============================================================
-- Customer & Regional Performance Analysis
-- ============================================================
-- ============================================================
-- Which customers generate the highest sales?
-- ============================================================

SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
GROUP BY customer_name
ORDER BY total_sales DESC
LIMIT 10;
-- ============================================================
-- Which customers generate the highest profit?
-- ============================================================

SELECT
    customer_name,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY customer_name
ORDER BY total_profit DESC
LIMIT 10;
-- ============================================================
-- Which countries generate the highest sales?
-- ============================================================

SELECT
    country,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
GROUP BY country
ORDER BY total_sales DESC
LIMIT 10;
-- ============================================================
-- Which countries generate the highest profit?
-- ============================================================

SELECT
    country,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY country
ORDER BY total_profit DESC
LIMIT 10;
-- ============================================================
-- Which markets generate the highest sales?
-- ============================================================

SELECT
    market,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
GROUP BY market
ORDER BY total_sales DESC;
-- ============================================================
-- Which markets generate the highest profit?
-- ============================================================

SELECT
    market,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY market
ORDER BY total_profit DESC;

-- ============================================================
-- Operational Performance Analysis
-- ============================================================
-- ============================================================
-- Which products have high sales but low profit?
-- ============================================================

SELECT
    product_name,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY product_name
HAVING SUM(sales) > 30000
ORDER BY total_profit ASC
LIMIT 10;
-- ============================================================
-- Which categories have the highest average discount?
-- ============================================================

SELECT
    category,
    ROUND(AVG(discount)*100,2) AS average_discount_percentage
FROM final_retail_dataset
GROUP BY category
ORDER BY average_discount_percentage DESC;
-- ============================================================
-- Which shipping mode generates the highest profit?
-- ============================================================

SELECT
    ship_mode,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY ship_mode
ORDER BY total_profit DESC;
-- ============================================================
-- Which order priorities generate the highest sales?
-- ============================================================

SELECT
    order_priority,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
GROUP BY order_priority
ORDER BY total_sales DESC;

-- ============================================================
-- Which year generated the highest sales and profit?
-- ============================================================

SELECT
    year,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY year
ORDER BY year;
-- ============================================================
-- Which countries have high sales but low profit?
-- ============================================================

SELECT
    country,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY country
HAVING SUM(sales) > 50000
ORDER BY total_profit ASC
LIMIT 10;
-- ============================================================
-- Which shipping mode generates the highest sales?
-- ============================================================

SELECT
    ship_mode,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
GROUP BY ship_mode
ORDER BY total_sales DESC;

-- ============================================================
-- Which discount band generates the highest sales?
-- ============================================================

SELECT
    discount_band,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
GROUP BY discount_band
ORDER BY total_sales DESC;
-- ============================================================
-- Which discount band generates the highest profit?
-- ============================================================

SELECT
    discount_band,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY discount_band
ORDER BY total_profit DESC;



-- ============================================================
-- Executive Recommendations & Business Intelligence Analysis
-- ============================================================

-- ============================================================
-- Which products have the highest profit margin?
-- ============================================================

SELECT
    product_name,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit,
    ROUND((SUM(profit)/SUM(sales))*100,2) AS profit_margin_percentage
FROM final_retail_dataset
GROUP BY product_name
HAVING SUM(sales) > 10000
ORDER BY profit_margin_percentage DESC
LIMIT 10;
-- ============================================================
-- Which categories have the highest profit margin?
-- ============================================================

SELECT
    category,
    ROUND((SUM(profit)/SUM(sales))*100,2) AS profit_margin_percentage
FROM final_retail_dataset
GROUP BY category
ORDER BY profit_margin_percentage DESC;
-- ============================================================
-- Which customers place the highest number of orders?
-- ============================================================

SELECT
    customer_name,
    COUNT(DISTINCT order_id) AS total_orders
FROM final_retail_dataset
GROUP BY customer_name
ORDER BY total_orders DESC
LIMIT 10;
-- ============================================================
-- Which countries have the highest average order value?
-- ============================================================

SELECT
    country,
    ROUND(SUM(sales)/COUNT(DISTINCT order_id),2) AS average_order_value
FROM final_retail_dataset
GROUP BY country
HAVING COUNT(DISTINCT order_id) > 20
ORDER BY average_order_value DESC
LIMIT 10;
-- ============================================================
-- Which months generate the highest sales?
-- ============================================================

SELECT
    month,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
GROUP BY month_no, month
ORDER BY month_no;
-- ============================================================
-- Which quarters generate the highest profit?
-- ============================================================

SELECT
    quarter,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
GROUP BY quarter
ORDER BY quarter;


-- ============================================================
-- Macroeconomic Impact Analysis (GDP & Inflation)
-- ============================================================
-- ============================================================
-- Does higher GDP growth lead to higher sales?
-- ============================================================

SELECT
    year,
    ROUND(AVG(gdp_growth),2) AS average_gdp_growth,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
WHERE gdp_growth IS NOT NULL
GROUP BY year
ORDER BY year;
-- ============================================================
-- Does inflation affect profitability?
-- ============================================================

SELECT
    year,
    ROUND(AVG(inflation_rate),2) AS average_inflation,
    ROUND(SUM(profit),2) AS total_profitS
FROM final_retail_dataset
WHERE inflation_rate IS NOT NULL
GROUP BY year
ORDER BY year;

-- ============================================================
-- Which years had the highest GDP growth and sales?
-- ============================================================

SELECT
    year,
    ROUND(AVG(gdp_growth),2) AS average_gdp_growth,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
WHERE gdp_growth IS NOT NULL
GROUP BY year
ORDER BY average_gdp_growth DESC;
-- ============================================================
-- Which years had the highest inflation and profit?
-- ============================================================

SELECT
    year,
    ROUND(AVG(inflation_rate),2) AS average_inflation,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
WHERE inflation_rate IS NOT NULL
GROUP BY year
ORDER BY average_inflation DESC;
-- ============================================================
-- Which countries achieved the highest sales despite inflation?
-- ============================================================

SELECT
    country,
    ROUND(AVG(inflation_rate),2) AS average_inflation,
    ROUND(SUM(sales),2) AS total_sales
FROM final_retail_dataset
WHERE inflation_rate IS NOT NULL
GROUP BY country
ORDER BY total_sales DESC
LIMIT 10;
-- ============================================================
-- Which countries achieved the highest profit despite inflation?
-- ============================================================

SELECT
    country,
    ROUND(AVG(inflation_rate),2) AS average_inflation,
    ROUND(SUM(profit),2) AS total_profit
FROM final_retail_dataset
WHERE inflation_rate IS NOT NULL
GROUP BY country
ORDER BY total_profit DESC
LIMIT 10;
